server:
  port: 8090

spring:
  application:
    name: Book Sale System
  datasource:
    username: book
    password: a123456
    url: jdbc:mysql://localhost:3306/book_sale_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  jpa:
    show-sql: true
  mvc:
    favicon:
      enabled: false
  redis:
    host: 127.0.0.1 #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    database: 0 #Redis数据库索引（默认为0）
    timeout: 18000000 #连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 20 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 5 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接

aliyun:
  endpoint: oss-cn-chengdu.aliyuncs.com
  accessKeyId: LTAI4FediEdQ2ZNtkTGNuYyp
  AccessKeySecret: oDAVk75LBl6Ag4QcgC1qpSRq9LxzQV
  bucketName: book-sale-system
info:
  app:
    name: ${spring.application.name}
    description: Book Sale System
    version: 1.0.0